version: '3.8'

services:
  gpu-acceleration-tests:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    restart: unless-stopped
    container_name: gpu-acceleration-tests
